// Pure simulation: metres, +x east, +z south, yaw 0 faces north.
export const CELL=5,SIZE=7,RADIUS=.22;
export function rng(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
export function makeMaze(seed){const random=rng(seed),cells=Array.from({length:SIZE*SIZE},(_,i)=>({x:i%SIZE,z:Math.floor(i/SIZE),open:[false,false,false,false]})),seen=new Set([0]),stack=[0],dirs=[[0,-1],[1,0],[0,1],[-1,0]];while(stack.length){const i=stack.at(-1),c=cells[i],options=[];dirs.forEach(([dx,dz],d)=>{let x=c.x+dx,z=c.z+dz;if(x>=0&&x<SIZE&&z>=0&&z<SIZE&&!seen.has(z*SIZE+x))options.push([d,z*SIZE+x])});if(!options.length){stack.pop();continue}const[d,j]=options[Math.floor(random()*options.length)];c.open[d]=true;cells[j].open[(d+2)%4]=true;seen.add(j);stack.push(j)}// Braided passages preserve all tree edges.
for(let k=0;k<9;k++){const i=Math.floor(random()*cells.length),c=cells[i],d=random()<.5?1:2;const x=c.x+dirs[d][0],z=c.z+dirs[d][1];if(x<SIZE&&z<SIZE){c.open[d]=true;cells[z*SIZE+x].open[(d+2)%4]=true}}
const dist=Array(cells.length).fill(Infinity),parent=Array(cells.length).fill(-1),q=[0];dist[0]=0;for(let k=0;k<q.length;k++){let i=q[k],c=cells[i];c.open.forEach((v,d)=>{if(v){const[dx,dz]=dirs[d],j=(c.z+dz)*SIZE+c.x+dx;if(dist[j]===Infinity){dist[j]=dist[i]+1;parent[j]=i;q.push(j)}}})}let goal=SIZE-1;for(let z=0;z<SIZE;z++){let i=z*SIZE+SIZE-1;if(dist[i]>dist[goal])goal=i}const route=[];for(let i=goal;i>=0;i=parent[i])route.unshift(i);return{seed:seed>>>0,cells,goal,route,dist,doorX:SIZE*CELL,doorZ:(cells[goal].z+.5)*CELL}}
export class Game{
constructor(seed=1){this.reset(seed)}
reset(seed){this.maze=makeMaze(seed);this.player={x:2.5,z:2.5,yaw:0,pitch:0};this.mode='menu';this.elapsed=0;this.food=100;this.hydration=100;this.door=0;this.doorTarget=0;this.changed=false;this.entered=false;this.loops=0;this.approach=0;this.noteRead=false;this.exitAnnounced=false;this.events=[];this.items=Array.from({length:4},(_,i)=>({id:`food-${i+1}`,kind:'food',state:'inventory',x:0,z:0,area:'maze'}));this.items.push(...Array.from({length:2},(_,i)=>({id:`water-${i+1}`,kind:'water',state:'world',x:this.maze.doorX+4.25,z:this.maze.doorZ-.8+i*.5,area:'room'})));this.obstacles=[{x:this.maze.doorX+4.4,z:this.maze.doorZ+.5,w:.8,d:2.7}];this.walls=[];const add=(x,z,w,d)=>this.walls.push({x,z,w,d});for(const c of this.maze.cells){const x=c.x*CELL,z=c.z*CELL;if(!c.open[0]&&!(c.x===0&&c.z===0))add(x+2.5,z,5,.16);if(!c.open[3])add(x,z+2.5,.16,5);if(c.x===SIZE-1&&c.z!==this.maze.cells[this.maze.goal].z)add(x+5,z+2.5,.16,5);if(c.z===SIZE-1)add(x+2.5,z+5,5,.16)}add(0,-5,.16,10);add(5,-5,.16,10);add(2.5,-10,5,.16);const dx=this.maze.doorX,dz=this.maze.doorZ;add(dx,dz-1.7,.16,1.6);add(dx,dz+1.7,.16,1.6);add(dx+3,dz-2.5,6,.16);add(dx+3,dz+2.5,6,.16);add(dx+6,dz,.16,5);return this}
start(){this.mode='playing';this.events.push('你带了食物，却忘了水。可以放下一份，记住来路。')}
inRoom(){return this.player.x>this.maze.doorX+RADIUS+.1}
inventory(kind){return this.items.filter(i=>i.kind===kind&&i.state==='inventory')}
collides(x,z){const m=this.maze,r=RADIUS;if(this.changed&&x<m.doorX){if(x<m.doorX-9.5||Math.abs(z-m.doorZ)>1.2-r)return true;return this.doorCollision(x,z)}if(x<r||z<-10+r||z>SIZE*CELL-r)return true;if(z<0&&x>5-r)return true;if(x>m.doorX&&((x>m.doorX+6-r)||Math.abs(z-m.doorZ)>2.5-r))return true;if([...this.walls,...this.obstacles].some(w=>Math.abs(x-w.x)<w.w/2+r&&Math.abs(z-w.z)<w.d/2+r))return true;return this.doorCollision(x,z)}
doorCollision(x,z){const m=this.maze; // A hinged solid leaf, tested in its local frame.
const a=this.door*Math.PI/2,dx=x-m.doorX,dz=z-(m.doorZ-.8),lx=Math.cos(a)*dx-Math.sin(a)*dz,lz=Math.sin(a)*dx+Math.cos(a)*dz;return Math.abs(lx)<.055+RADIUS&&lz> -RADIUS&&lz<1.6+RADIUS}
move(dx,dz){const steps=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.09));for(let k=0;k<steps;k++){const p=this.player,oldZ=p.z;let x=p.x+dx/steps,z=p.z+dz/steps;if(!this.collides(x,p.z))p.x=x;if(!this.collides(p.x,z))p.z=z;if(!this.changed&&oldZ>=-7.5&&p.z< -7.5&&p.x>RADIUS&&p.x<5-RADIUS){p.z+=10;this.loops++;this.events.push(this.items.some(i=>i.kind==='food'&&i.state==='world'&&Math.hypot(i.x-p.x,i.z-p.z)<4)?'灯声停了一瞬。前面那份食物，看起来很熟悉。':'这一段灯声，好像听过。换条路试试。')}
if(this.changed&&p.x<this.maze.doorX-8.3){this.mode='won';this.events.push('exit');break}}}
update(dt,input={}){if(this.mode!=='playing')return;dt=Math.min(.05,Math.max(0,dt));this.elapsed+=dt;const speed=input.sprint&&this.hydration>15?3.25:2.05;let f=input.forward||0,s=input.strafe||0,n=Math.max(1,Math.hypot(f,s));f/=n;s/=n;this.move((Math.sin(this.player.yaw)*f+Math.cos(this.player.yaw)*s)*speed*dt,(-Math.cos(this.player.yaw)*f+Math.sin(this.player.yaw)*s)*speed*dt);this.food=Math.max(0,this.food-dt*(input.sprint?.026:.014));this.hydration=Math.max(0,this.hydration-dt*(input.sprint?.07:.035));if(this.hydration<=0||this.food<=0){this.mode='lost';this.events.push('lost');return}if(this.inRoom()&&!this.entered){this.entered=true;this.events.push('木门外，传来很轻的脚步声。先把门关好。')}if(this.entered&&!this.changed)this.approach+=dt;if(this.door!==this.doorTarget){const old=this.door;let proposed=this.door+Math.sign(this.doorTarget-this.door)*dt*1.5;this.door=Math.max(0,Math.min(1,proposed));if(this.doorTarget===0&&this.doorCollision(this.player.x,this.player.z)){this.door=old;this.doorTarget=1;this.events.push('你挡住了门。再往房间里走一点。')}}if(this.entered&&!this.changed&&this.door===0&&this.doorTarget===0&&this.inRoom()){this.changed=true;this.events.push('门完全关上了。脚步声消失。')} }
nearDoor(){return Math.hypot(this.player.x-this.maze.doorX,this.player.z-this.maze.doorZ)<2.35}
nearNote(){return this.inRoom()&&Math.hypot(this.player.x-(this.maze.doorX+4.35),this.player.z-(this.maze.doorZ+1.4))<1.6}
lineClear(x,z){const p=this.player,dist=Math.hypot(x-p.x,z-p.z),steps=Math.ceil(dist/.1);for(let k=1;k<steps;k++){const qx=p.x+(x-p.x)*k/steps,qz=p.z+(z-p.z)*k/steps;if(this.walls.some(w=>Math.abs(qx-w.x)<w.w/2&&Math.abs(qz-w.z)<w.d/2)||this.doorCollision(qx,qz))return false}return true}
nearestItem(){return this.items.filter(i=>i.state==='world'&&(this.changed?i.area==='room':true)).filter(i=>Math.hypot(i.x-this.player.x,i.z-this.player.z)<1.6&&this.lineClear(i.x,i.z)).sort((a,b)=>Math.hypot(a.x-this.player.x,a.z-this.player.z)-Math.hypot(b.x-this.player.x,b.z-this.player.z))[0]}
interact(){if(this.mode!=='playing')return;const item=this.nearestItem();if(item){item.state='inventory';this.events.push(item.kind==='food'?`拾回了食物 ${item.id.slice(-1)}。`:'找到一小瓶饮用水。');return 'pickup'}if(this.nearNote()){this.noteRead=true;this.mode='note';return 'note'}if(this.nearDoor()){this.doorTarget=this.doorTarget>.5?0:1;return 'door'}return null}
drop(){if(this.mode!=='playing')return;const i=this.inventory('food')[0];if(!i){this.events.push('没有食物可以放下了。');return}const p=this.player;const x=p.x+Math.sin(p.yaw)*.7,z=p.z-Math.cos(p.yaw)*.7;if(this.collides(x,z)){this.events.push('这里太靠近墙了。');return}Object.assign(i,{state:'world',x,z,area:this.inRoom()?'room':'maze'});this.events.push(`放下了食物 ${i.id.slice(-1)}。它会留在原地。`);return i.id}
consume(kind){if(this.mode!=='playing')return;const item=this.inventory(kind)[0];if(!item){this.events.push(kind==='water'?'没有饮用水。':'没有食物了。');return}if(kind==='food'&&this.food>98){this.events.push('现在还不饿。');return}if(kind==='water'&&this.hydration>98){this.events.push('现在还不渴。');return}item.state='consumed';if(kind==='food'){this.food=Math.min(100,this.food+28);this.hydration=Math.max(0,this.hydration-2);this.events.push('吃完了一份干粮。有些口干。')}else{this.hydration=Math.min(100,this.hydration+38);this.events.push('喝完了一小瓶水。')}return item.id}
pause(){if(this.mode==='playing')this.mode='paused'}resume(){if(this.mode==='paused'||this.mode==='note')this.mode='playing'}
snapshot(){return{seed:this.maze.seed,mode:this.mode,player:{...this.player},food:this.food,hydration:this.hydration,elapsed:this.elapsed,door:this.door,doorTarget:this.doorTarget,changed:this.changed,loops:this.loops,items:this.items.map(i=>({...i}))}}
}
