// Deterministic, addressable world data. Only a small LRU of procedural chunks is
// resident; item state remains in Game.items and is never regenerated by a chunk.
export const WORLD_CELL=5,CHUNK_CELLS=11,CHUNK_METRES=55,DATA_CACHE_LIMIT=16;
export const RENDER_CELLS=7,RENDER_METRES=35,RENDER_RADIUS=2,RENDER_LIMIT=25,VIEW_REGION_LIMIT=49;
export const DIRECTIONS=[[0,-1],[1,0],[0,1],[-1,0]];
export const keyOf=(x,z)=>`${x},${z}`;
function hash(seed,x,z,salt=0){let h=(seed^Math.imul(x,0x45d9f3b)^Math.imul(z,0x119de1f3)^salt)>>>0;h=Math.imul(h^h>>>16,0x7feb352d);h=Math.imul(h^h>>>15,0x846ca68b);return(h^h>>>16)>>>0}
function random(seed){let a=seed;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
export class ChunkWorld{
 constructor(seed,landmark){this.seed=seed>>>0;this.landmark=landmark;this.cache=new Map();this.generated=0;this.evicted=0}
 // A seam is named by its north/west coordinate, never by request order. Its
 // counterpart therefore agrees, including across zero and negative coordinates.
 portal(cx,cz,d){let x=cx,z=cz,axis=d%2;if(d===0)z--;if(d===3)x--;
  let slot=hash(this.seed,x,z,axis?0x518f3251:0x13c6ef37)%CHUNK_CELLS;
  const goalZ=this.landmark.cells[this.landmark.goal].z;
  if(axis&&x===0&&z===0&&slot===goalZ)slot=(slot+1)%CHUNK_CELLS;
  if(!axis&&x===1&&((z===-1&&goalZ===0)||(z===0&&goalZ===CHUNK_CELLS-1))&&slot<2)slot+=2;
  return slot;
 }
 chunk(cx,cz){const key=keyOf(cx,cz);if(this.cache.has(key)){const value=this.cache.get(key);this.cache.delete(key);this.cache.set(key,value);return value}
  const central=cx===0&&cz===0,n=CHUNK_CELLS,ox=cx*n,oz=cz*n,goalZ=this.landmark.cells[this.landmark.goal].z;
  const cells=Array.from({length:n*n},(_,i)=>{const x=i%n,z=Math.floor(i/n),reserved=cx===1&&cz===0&&x<2&&z===goalZ;return{x:x+ox,z:z+oz,active:!reserved,open:central?[...this.landmark.cells[i].open]:[false,false,false,false]}});
  if(!central){const rand=random(hash(this.seed,cx,cz,0xe135c271)),seen=new Set(),start=cells.findIndex(c=>c.active),stack=[start];seen.add(start);
   while(stack.length){const i=stack.at(-1),x=i%n,z=Math.floor(i/n),options=[];
    DIRECTIONS.forEach(([dx,dz],d)=>{const xx=x+dx,zz=z+dz,j=zz*n+xx;if(xx>=0&&xx<n&&zz>=0&&zz<n&&cells[j].active&&!seen.has(j))options.push([j,d])});
    if(!options.length){stack.pop();continue}const[j,d]=options[Math.floor(rand()*options.length)];cells[i].open[d]=true;cells[j].open[(d+2)%4]=true;seen.add(j);stack.push(j);
   }
   for(let k=0;k<8;k++){const i=Math.floor(rand()*cells.length),x=i%n,z=Math.floor(i/n),d=rand()<.5?1:2,[dx,dz]=DIRECTIONS[d],j=(z+dz)*n+x+dx;if(x+dx<n&&z+dz<n&&cells[i].active&&cells[j].active){cells[i].open[d]=true;cells[j].open[(d+2)%4]=true}}
  }
  for(let d=0;d<4;d++){const s=this.portal(cx,cz,d),i=d===0?s:d===1?s*n+n-1:d===2?(n-1)*n+s:s*n;cells[i].open[d]=true}
  for(const c of cells){c.walls=[];if(!c.active)continue;
   c.open.forEach((open,d)=>{if(open)return;if(central&&c.x===n-1&&c.z===goalZ&&d===1)return;
    const[dx,dz]=DIRECTIONS[d];c.walls.push({x:(c.x+.5+dx*.5)*WORLD_CELL,z:(c.z+.5+dz*.5)*WORLD_CELL,w:d%2?.16:WORLD_CELL,d:d%2?WORLD_CELL:.16,key:`${d%2}:${d===3?c.x-1:c.x},${d===0?c.z-1:c.z}`})});
   if(central){const f=this.landmark.folds.find(f=>f.x===c.x&&f.z===c.z);if(f)c.walls.push({x:f.px,z:f.z*WORLD_CELL+2.5,w:2.6,d:.16,key:`fold:${f.id}`})}
  }
  // Manila occupies 6 m of a 10 m reserved strip. Its persistent side walls
  // replace the overlapping procedural wall portions, avoiding coplanar faces.
  const roomX=this.landmark.doorX,roomZ=this.landmark.doorZ;
  for(const c of cells)c.walls=c.walls.flatMap(w=>{
   if(w.w<=w.d||Math.abs(Math.abs(w.z-roomZ)-2.5)>.001||w.x+w.w/2<=roomX||w.x-w.w/2>=roomX+6)return[w];
   const a=w.x-w.w/2,b=w.x+w.w/2,out=[];if(a<roomX)out.push({...w,x:(a+roomX)/2,w:roomX-a});if(b>roomX+6)out.push({...w,x:(roomX+6+b)/2,w:b-roomX-6});return out;
  });
  const result={key,cx,cz,cells};this.cache.set(key,result);this.generated++;
  while(this.cache.size>DATA_CACHE_LIMIT){this.cache.delete(this.cache.keys().next().value);this.evicted++}return result;
 }
 cell(x,z){const special=this.escapeLayout?.lookup.get(keyOf(x,z));if(special)return special;const cx=Math.floor(x/CHUNK_CELLS),cz=Math.floor(z/CHUNK_CELLS),chunk=this.chunk(cx,cz);return chunk.cells[(z-cz*CHUNK_CELLS)*CHUNK_CELLS+x-cx*CHUNK_CELLS]}
 cellsInRect(x0,z0,x1,z1){const out=[];for(let z=z0;z<=z1;z++)for(let x=x0;x<=x1;x++)out.push(this.cell(x,z));return out}
 wallsInRect(x0,z0,x1,z1){const result=new Map();for(const c of this.cellsInRect(x0,z0,x1,z1))for(const w of c.walls)result.set(w.key,w);return [...result.values()]}
 wallsNear(x,z,padding=.3){return this.wallsInRect(Math.floor((x-padding)/WORLD_CELL),Math.floor((z-padding)/WORLD_CELL),Math.floor((x+padding)/WORLD_CELL),Math.floor((z+padding)/WORLD_CELL))}
 stats(){return{resident:this.cache.size,limit:DATA_CACHE_LIMIT,generated:this.generated,evicted:this.evicted}}
}
// Conservative 360-degree visibility for the opaque, floor-to-ceiling corridor
// grid. `reach` is a world-space radius, NOT the camera's far-plane distance:
// use far * sqrt(1 + tan(verticalFov / 2)^2 * (1 + aspect^2)) to include every
// perspective corner at every yaw/pitch. No finite set of rays can cover the
// arbitrarily thin views through consecutive portals, so propagate their whole
// angular intervals instead. Fold walls, wall thickness and Manila's separate
// room walls are ignored here; removing an occluder can only add required cells.
//
// The returned cell coordinates include both sides of every visible boundary.
// Callers still need a one-cell halo when assigning shared wall/trim ownership
// to render regions. Do not cache by rounded player positions: a tiny movement
// can reveal a new corridor. A null result means the caller MUST use its safe
// full-frustum fallback, never a partial result. Limits bound reads, storage and
// interval work even in open rooms or adversarial cyclic layouts.
export function visibleCorridorCells(world,x,z,reach,{maxCells=2048,maxSteps=16384}={}){
 if(!world||typeof world.cell!=='function'||![x,z,reach].every(Number.isFinite)||reach<0||!Number.isInteger(maxCells)||maxCells<1||maxCells>16384||!Number.isInteger(maxSteps)||maxSteps<1||maxSteps>262144)return null;
 const tau=2*Math.PI,angleMargin=1e-10;
 // At large coordinates rounding can swallow portal widths. Decline that case
 // instead of relying on inaccurate angles. The small positional margin also
 // seeds both sides when the eye is exactly on (or nearly on) a grid boundary.
 const scale=Math.max(1,Math.abs(x),Math.abs(z),reach),positionMargin=Math.max(1e-7,scale*Number.EPSILON*32);
 if(positionMargin>1e-3)return null;
 const cx=Math.floor(x/WORLD_CELL),cz=Math.floor(z/WORLD_CELL),cells=new Map(),visible=new Map(),coverage=new Map(),queue=[];
 let work=0,failed=false;
 const spend=()=>{if(++work>maxSteps){failed=true;return false}return true};
 const read=(xx,zz)=>{
  const key=keyOf(xx,zz);if(cells.has(key))return cells.get(key);
  if(cells.size>=maxCells){failed=true;return null}
  const cell=world.cell(xx,zz);
  if(!cell||cell.x!==xx||cell.z!==zz||!Array.isArray(cell.open)||cell.open.length!==4){failed=true;return null}
  cells.set(key,cell);return cell;
 };
 const include=(xx,zz)=>{const key=keyOf(xx,zz);if(!visible.has(key)){if(visible.size>=maxCells){failed=true;return}visible.set(key,{x:xx,z:zz})}};
 const enqueue=(xx,zz,lo,hi)=>{
  if(failed||!spend())return;
  const key=keyOf(xx,zz),prior=coverage.get(key)||[];
  // Exact containment is important: epsilon-based "already visited" tests can
  // accidentally discard a newly exposed sliver. Numerical slack is applied
  // only outwards to portal bounds, never by shrinking a newly reached cone.
  for(const interval of prior){if(!spend())return;if(lo>=interval[0]&&hi<=interval[1])return}
  const merged=[];let a=lo,b=hi,inserted=false;
  for(const interval of prior){
   if(!spend())return;
   if(interval[1]<a)merged.push(interval);
   else if(interval[0]>b){if(!inserted){merged.push([a,b]);inserted=true}merged.push(interval)}
   else{a=Math.min(a,interval[0]);b=Math.max(b,interval[1])}
  }
  if(!inserted)merged.push([a,b]);
  coverage.set(key,merged);queue.push({x:xx,z:zz,lo,hi});include(xx,zz);
 };
 const portalIntervals=(ax,az,bx,bz)=>{
  // Closest point on these axis-aligned segments, relative to the eye.
  const nearX=Math.max(Math.min(ax,bx),Math.min(Math.max(ax,bx),x)),nearZ=Math.max(Math.min(az,bz),Math.min(Math.max(az,bz),z));
  const distance=Math.hypot(nearX-x,nearZ-z);
  if(distance>reach+positionMargin)return[];
  if(distance<=positionMargin)return[[0,tau]];
  let a=Math.atan2(az-z,ax-x),b=Math.atan2(bz-z,bx-x);
  if(a<0)a+=tau;if(b<0)b+=tau;
  let span=(b-a+tau)%tau;if(span>Math.PI){a=b;span=tau-span}
  a-=angleMargin;let end=a+span+2*angleMargin;
  if(a<0)return[[0,end],[a+tau,tau]];
  if(end>tau)return[[a,tau],[0,end-tau]];
  return[[a,end]];
 };
 // A cell boundary belongs to both closed cells at the exact boundary. Seeding
 // both also covers floating-point classification immediately beside it.
 const xs=[cx],zs=[cz],left=cx*WORLD_CELL,top=cz*WORLD_CELL;
 if(x-left<=positionMargin)xs.push(cx-1);else if(left+WORLD_CELL-x<=positionMargin)xs.push(cx+1);
 if(z-top<=positionMargin)zs.push(cz-1);else if(top+WORLD_CELL-z<=positionMargin)zs.push(cz+1);
 for(const xx of xs)for(const zz of zs)enqueue(xx,zz,0,tau);
 for(let head=0;head<queue.length&&!failed;head++){
  if(!spend())break;
  const state=queue[head],cell=read(state.x,state.z);if(!cell)break;
  const x0=state.x*WORLD_CELL,z0=state.z*WORLD_CELL,x1=x0+WORLD_CELL,z1=z0+WORLD_CELL;
  const edges=[[x0,z0,x1,z0],[x1,z0,x1,z1],[x0,z1,x1,z1],[x0,z0,x0,z1]];
  for(let d=0;d<4&&!failed;d++){
   if(!spend())break;
   // A straight ray's x/z signs never reverse. Ignore the entry-facing side
   // of cells wholly beyond the eye; this prevents cyclic backtracking without
   // excluding any possible outward sightline (including boundary tolerances).
   if((d===0&&z0>z+positionMargin)||(d===1&&x1<x-positionMargin)||(d===2&&z1<z-positionMargin)||(d===3&&x0>x+positionMargin))continue;
   const intervals=portalIntervals(...edges[d]),crossings=[];
   for(const[lo,hi]of intervals){const a=Math.max(lo,state.lo),b=Math.min(hi,state.hi);if(a<=b)crossings.push([a,b])}
   if(!crossings.length)continue;
   const[dx,dz]=DIRECTIONS[d],xx=state.x+dx,zz=state.z+dz;
   include(xx,zz);const next=read(xx,zz);if(!next)break;
   // Reserved Manila cells have no procedural walls; its entrance also omits
   // the otherwise closed maze side. Treat every side adjoining that strip as
   // open. The persistent room geometry remains an additional true occluder.
   const open=cell.active===false||next.active===false||cell.open[d]||next.open[(d+2)%4];
   if(open)for(const[a,b]of crossings)enqueue(xx,zz,a,b);
  }
 }
 return failed?null:[...visible.values()];
}
// The same small scheduler is used by the browser, not a test-only model. Build
// steps yield after each surface/cell. A pending region never becomes traversable.
export class RenderChunkStream{
 constructor({create,dispose,clock=()=>performance.now(),radius=RENDER_RADIUS,capacity=VIEW_REGION_LIMIT}){this.create=create;this.dispose=dispose;this.clock=clock;this.radius=radius;this.capacity=Number.isFinite(capacity)?Math.max(1,Math.min(VIEW_REGION_LIMIT,Math.floor(capacity))):VIEW_REGION_LIMIT;this.records=new Map();this.desired=new Map();this.required=new Set();this.requestMode=false;this.center=null;this.completed=0;this.disposed=0;this.maxResident=0}
 // Compatibility window for simulation tests and callers that need a square.
 update(x,z){const cx=Math.floor(x/RENDER_METRES),cz=Math.floor(z/RENDER_METRES),center=keyOf(cx,cz);if(!this.requestMode&&center===this.center)return;this.requestMode=false;this.center=center;this.cx=cx;this.cz=cz;
  const desired=new Map();for(let dz=-this.radius;dz<=this.radius;dz++)for(let dx=-this.radius;dx<=this.radius;dx++)desired.set(keyOf(cx+dx,cz+dz),{x:cx+dx,z:cz+dz,required:true});
  for(const[key,record]of this.records)if(!desired.has(key)){this.release(record);this.records.delete(key)}
  for(const[key,point]of desired)if(!this.records.has(key))this.records.set(key,{key,...point,ready:false,iterator:null,value:null});
  this.desired=desired;this.required=new Set(desired.keys());this.maxResident=Math.max(this.maxResident,this.records.size);
 }
 // Camera requests are transactional: never silently omit a visible region.
 // Completed, unrequested regions remain an LRU until new work needs their room.
 request(points,x,z){
  if(!Array.isArray(points)||!Number.isFinite(x)||!Number.isFinite(z))return false;
  const unique=new Map();for(const point of points){if(!point||!Number.isInteger(point.x)||!Number.isInteger(point.z))return false;const key=keyOf(point.x,point.z),prior=unique.get(key);if(prior){if(point.required)prior.required=true}else unique.set(key,{x:point.x,z:point.z,required:!!point.required})}
  const required=[...unique.values()].filter(point=>point.required);if(required.length>this.capacity)return false;
  const selected=[...required,...[...unique.values()].filter(point=>!point.required).slice(0,this.capacity-required.length)],desired=new Map(selected.map(point=>[keyOf(point.x,point.z),point]));
  for(const[key,record]of this.records)if(!record.ready&&!desired.has(key)){this.release(record);this.records.delete(key)}
  let missing=0;for(const key of desired.keys())if(!this.records.has(key))missing++;
  for(const[key,record]of this.records){if(this.records.size+missing<=this.capacity)break;if(!desired.has(key)){this.release(record);this.records.delete(key)}}
  // Map order records the most recent requests, independently of build priority.
  for(const[key,point]of desired){const record=this.records.get(key)||{key,...point,ready:false,iterator:null,value:null};record.required=point.required;this.records.delete(key);this.records.set(key,record)}
  this.requestMode=true;this.cx=Math.floor(x/RENDER_METRES);this.cz=Math.floor(z/RENDER_METRES);this.center=keyOf(this.cx,this.cz);this.desired=desired;this.required=new Set(required.map(point=>keyOf(point.x,point.z)));this.maxResident=Math.max(this.maxResident,this.records.size);return true;
 }
 requiredReady(){return [...this.required].every(key=>this.records.get(key)?.ready===true)}
 release(record){record.iterator?.return?.();if(record.value)this.dispose(record.value);record.iterator=null;record.value=null;this.disposed++}
 process(budget=3,maxSteps=24){const start=this.clock();let steps=0;
  while(steps<maxSteps){
   const pending=[...this.desired.keys()].map(key=>this.records.get(key)).filter(r=>r&&!r.ready);
   if(!this.requestMode)pending.sort((a,b)=>Math.hypot(a.x-this.cx,a.z-this.cz)-Math.hypot(b.x-this.cx,b.z-this.cz));
   // Newly visible work preempts optional prewarming at the next small yield.
   // Keep the optional iterator for reuse, within the same hard resident cap.
   const urgent=this.requestMode?pending.filter(r=>this.required.has(r.key)):pending;
   const candidates=urgent.length?urgent:pending;
   const next=candidates.find(r=>r.iterator)||candidates[0];if(!next)break;
   if(!next.iterator){const task=this.create(next.x,next.z);next.value=task.value;next.iterator=task.iterator}
   const result=next.iterator.next();steps++;
   if(result.done){next.ready=true;next.iterator=null;this.completed++}
   if(this.clock()-start>=budget)break;
  }return steps;
 }
 clearRadius(x,z){
  if(!this.readyAt(x,z))return 0;let distance=Infinity;
  for(const record of this.records.values())if(record.ready)for(let d=0;d<4;d++){const[dx,dz]=DIRECTIONS[d];if(this.records.get(keyOf(record.x+dx,record.z+dz))?.ready)continue;const x0=record.x*RENDER_METRES,z0=record.z*RENDER_METRES,x1=x0+RENDER_METRES,z1=z0+RENDER_METRES;const nearestX=d===1?x1:d===3?x0:Math.max(x0,Math.min(x1,x)),nearestZ=d===0?z0:d===2?z1:Math.max(z0,Math.min(z1,z));distance=Math.min(distance,Math.hypot(x-nearestX,z-nearestZ))}return Number.isFinite(distance)?distance:0;
 }
 readyAt(x,z){return this.records.get(keyOf(Math.floor(x/RENDER_METRES),Math.floor(z/RENDER_METRES)))?.ready===true}
 clear(){for(const record of this.records.values())this.release(record);this.records.clear();this.desired.clear();this.required.clear();this.center=null}
 stats(){return{resident:this.records.size,ready:[...this.records.values()].filter(r=>r.ready).length,pending:[...this.records.values()].filter(r=>!r.ready).length,limit:this.requestMode?this.capacity:(this.radius*2+1)**2,completed:this.completed,disposed:this.disposed,maxResident:this.maxResident}}
}
