import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import vm from'node:vm';import * as THREE from'../dist/vendor/three.module.min.js';import{Game}from'../dist/game.js';
const source=fs.readFileSync('dist/app.js','utf8').replace("import * as THREE from './vendor/three.module.min.js';",'').replace("import {Game} from './game.js';",'');
function boot(){const nodes=new Map(),listeners={},canvas2d={fillRect(){},fillText(){}};function element(id){if(!nodes.has(id))nodes.set(id,{id,hidden:id!=='menu',disabled:id==='continue',style:{},textContent:'',classList:{add(){},remove(){}},addEventListener(n,fn){(listeners[id+':'+n]??=[]).push(fn)},setAttribute(){},setPointerCapture(){},getContext:()=>canvas2d,getBoundingClientRect:()=>({left:22,top:400,width:112,height:112})});return nodes.get(id)};let frame;const document={getElementById:element,createElement:()=>element('canvas-'+nodes.size),addEventListener(n,fn){listeners['document:'+n]=[fn]},exitPointerLock(){},hidden:false};let rendered;
class Renderer{constructor(){this.shadowMap={};}setPixelRatio(v){this.ratio=v}setSize(w,h){this.width=w;this.height=h}render(scene,camera){rendered={scene,camera}}};class Loader{load(){return new THREE.Texture()}}
const context={THREE:{...THREE,WebGLRenderer:Renderer,TextureLoader:Loader},Game,document,window:{addEventListener(n,fn){listeners['window:'+n]=[fn]}},navigator:{},performance:{now:()=>0},crypto:{getRandomValues:a=>{a[0]=42;return a}},matchMedia:()=>({matches:true}),innerWidth:390,innerHeight:844,devicePixelRatio:3,requestAnimationFrame:fn=>frame=fn,setTimeout:fn=>fn(),console,AbortController};vm.createContext(context);vm.runInContext(source,context);return{context,element,listeners,frame:now=>frame(now),getRender:()=>rendered,eval:s=>vm.runInContext(s,context)}}
test('app boots and follows menu / pause / continue / settings / restart with a mocked DOM and GPU',()=>{const app=boot();assert.equal(app.element('error').hidden,true);
assert.equal(app.eval('game.mode'),'menu');app.frame(100);assert.equal(app.getRender().camera.position.x,22.5);assert.equal(app.eval('hasRun'),false);app.element('start').onclick();assert.equal(app.eval('game.mode'),'playing');assert.equal(app.eval('game.maze.seed'),42);app.element('pause').onclick();assert.equal(app.eval('game.mode'),'paused');app.element('main-menu').onclick();assert.equal(app.eval('game.mode'),'menu');assert.equal(app.element('continue').disabled,false);app.element('continue').onclick();assert.equal(app.eval('game.mode'),'playing');app.element('sound-toggle').onclick();assert.equal(app.eval('soundEnabled'),false);app.element('quality-toggle').onclick();assert.equal(app.eval('renderScale'),.75);app.element('restart').onclick();assert.equal(app.eval('game.items.length'),6);assert.equal(app.eval('game.inventory("food").length'),4);app.frame(200);assert.equal(app.eval('renderer.shadowMap.enabled'),false);assert.equal(app.eval('renderer.shadowMap.autoUpdate'),false)});
test('lighting stays bounded, instancing retains static geometry, and resolution budget is enforced',()=>{const app=boot();app.frame(100);const{scene}=app.getRender();let lights=0,points=0,instanced=0,instances=0;scene.traverse(o=>{if(o.isLight)lights++;if(o.isPointLight)points++;if(o.isInstancedMesh){instanced++;instances+=o.count}});assert.equal(lights,2);assert.equal(points,0);assert(instanced>=6);assert(instances>900);for(const[w,h,dpr,coarse]of [[390,844,3,true],[1366,1024,2,true],[3840,2160,2,false]]){const r=app.eval(`pixelRatio(${w},${h},${dpr},${coarse})`);assert(w*h*r*r<=(coarse?1100000:2000000)+.01);assert(r<=(coarse?1.35:1.6))}});
test('separate touch pointers stop on cancellation and blur in mocked event dispatch',()=>{const app=boot();app.element('start').onclick();const event=(id,x,y)=>({pointerId:id,clientX:x,clientY:y,preventDefault(){}});app.listeners['stick:pointerdown'][0](event(11,100,420));assert.notEqual(app.eval('input.forward'),0);app.listeners['look:pointerdown'][0](event(22,220,380));app.listeners['look:pointermove'][0](event(22,230,380));assert(app.eval('game.player.yaw')>0);app.listeners['stick:pointercancel'][0](event(11,100,420));assert.equal(app.eval('input.forward'),0);app.listeners['window:blur'][0]();assert.equal(app.eval('game.mode'),'paused');assert.equal(app.eval('touch.look'),null);assert.equal(app.eval('touch.move'),null)});
