import test from 'node:test';import assert from 'node:assert/strict';import {Game,makeMaze,SIZE,CELL} from '../dist/game.js';
function tick(g,t,input={}){for(let i=0;i<t/.02;i++)g.update(.02,input)}
function walk(g,x,z){let guard=0;while(g.mode==='playing'&&Math.hypot(g.player.x-x,g.player.z-z)>.07&&guard++<10000){const dx=x-g.player.x,dz=z-g.player.z,l=Math.hypot(dx,dz);g.player.yaw=Math.atan2(dx,-dz);g.update(.02,{forward:Math.min(1,l/.041)})}assert(guard<10000,`blocked at ${JSON.stringify(g.player)} towards ${x},${z}`)}
test('100 seeds: deterministic 49-cell connected maze with reciprocal passages and physically traversable ordinary path',()=>{for(let seed=0;seed<100;seed++){const m=makeMaze(seed);assert.deepEqual(m,makeMaze(seed));assert(m.dist.every(Number.isFinite));assert.equal(m.cells.length,49);const dirs=[[0,-1],[1,0],[0,1],[-1,0]];for(const c of m.cells)c.open.forEach((v,d)=>{if(v){const[dx,dz]=dirs[d];assert(m.cells[(c.z+dz)*SIZE+c.x+dx].open[(d+2)%4])}});assert.equal(m.dist[m.goal],Math.max(...m.cells.filter(c=>c.x===6).map(c=>m.dist[c.z*7+c.x])));const g=new Game(seed);g.start();for(const i of m.route){const c=m.cells[i];walk(g,(c.x+.5)*5,(c.z+.5)*5)}assert(Math.hypot(g.player.x-(m.doorX-2.5),g.player.z-m.doorZ)<.1);assert(g.hydration>80);assert.equal(g.loops,0)}});
test('food identities conserved through drop, loop, pickup, consume',()=>{const g=new Game(42);g.start();assert.equal(g.inventory('water').length,0);assert.equal(g.items.filter(i=>i.kind==='water').length,2);const id=g.drop(),item=g.items.find(i=>i.id===id),pos={x:item.x,z:item.z};g.move(0,-10.3);assert.equal(g.loops,1);assert.deepEqual({x:item.x,z:item.z},pos);g.player.x=pos.x;g.player.z=pos.z+.3;assert.equal(g.interact(),'pickup');g.food=50;assert.equal(g.consume('food'),id);assert.equal(g.items.find(i=>i.id===id).state,'consumed');assert.equal(new Set(g.items.map(i=>i.id)).size,6);assert.equal(g.items.length,6)});
test('spatial loop only true forward boundary crossing; translation and yaw preserved',()=>{const g=new Game(9);g.start();g.player={x:3.1,z:-7.45,yaw:.36,pitch:.1};g.move(0,-.2);assert.equal(g.loops,1);assert(Math.abs(g.player.z-2.35)<1e-8);assert.equal(g.player.x,3.1);assert.equal(g.player.yaw,.36);g.move(.2,0);assert.equal(g.loops,1);g.player.z=-7.5;g.move(0,.1);assert.equal(g.loops,1)});
test('pause freezes all simulation and restart resets inventory/door',()=>{const g=new Game(3);g.start();g.drop();g.doorTarget=1;tick(g,1);g.pause();const snapshot=g.snapshot();tick(g,60,{forward:1,sprint:true});g.interact();g.drop();g.consume('water');assert.deepEqual(g.snapshot(),snapshot);g.reset(4);assert.equal(g.items.length,6);assert.equal(g.inventory('food').length,4);assert.equal(g.inventory('water').length,0);assert.equal(g.door,0);assert.equal(g.changed,false);assert.equal(g.mode,'menu')});
test('manual door, complete close only inside, finite water, next-room completion',()=>{for(const seed of [0,1,42,0xDEADBEEF]){const g=new Game(seed);g.start();const m=g.maze;for(const i of m.route){const c=m.cells[i];walk(g,(c.x+.5)*5,(c.z+.5)*5)}walk(g,m.doorX-1.25,m.doorZ);tick(g,2);assert.equal(g.door,0);assert(g.collides(m.doorX,m.doorZ));g.interact();tick(g,1);assert.equal(g.door,1);walk(g,m.doorX+2.1,m.doorZ);assert(g.entered);g.interact();tick(g,.25);assert.equal(g.changed,false);g.interact();tick(g,.7);assert.equal(g.changed,false);g.interact();tick(g,1);assert(g.changed);assert.equal(g.mode,'playing');walk(g,m.doorX+3.6,m.doorZ-.65);g.interact();g.interact();assert.equal(g.inventory('water').length,2);g.hydration=10;g.consume('water');g.consume('water');g.consume('water');assert.equal(g.inventory('water').length,0);assert.equal(g.items.filter(i=>i.kind==='water'&&i.state==='consumed').length,2);walk(g,m.doorX+2.1,m.doorZ);g.interact();tick(g,1);walk(g,m.doorX-8.4,m.doorZ);assert.equal(g.mode,'won')}});
test('walls prevent clipping even for large displacements',()=>{const g=new Game(7);g.start();g.move(-100,0);assert(g.player.x>.25);assert(!g.collides(g.player.x,g.player.z));g.player.x=2.5;g.player.z=-9.4;g.move(0,-100);assert(g.player.z>-9.7)});
