import test from 'node:test';
import assert from 'node:assert/strict';
import {LEVEL_ONE_AREAS,isLevelOneSheltered} from '../dist/level-one-layout.js';
import {prepareLevelOneDanger,resetLevelOneDanger,updateLevelOneDanger} from '../dist/level-one-danger.js';
const tick=(g,t)=>{for(let i=0;i<Math.round(t/.025);i++)updateLevelOneDanger(g,.025)};
function exposed(a){for(let z=a.bounds.maxZ-16;z>a.bounds.minZ+16;z--)if([-5,0,5].every(x=>!isLevelOneSheltered(x,z)))return{x:0,z};throw Error('No exposed test row')}
function make(a=LEVEL_ONE_AREAS[0]){return{zone:'level1',mode:'playing',player:{...exposed(a),yaw:0},events:[],level1:{area:a.id,phase:'lit',sprinting:false,danger:resetLevelOneDanger()},calls:0,collides(x,z,{radius=0,ignoreEntities}={}){assert.equal(ignoreEntities,true);this.calls++;const b=LEVEL_ONE_AREAS.find(a=>x>=a.bounds.minX&&x<=a.bounds.maxX&&z>=a.bounds.minZ&&z<=a.bounds.maxZ)?.bounds;return !b||x<b.minX+radius||x>b.maxX-radius||z<b.minZ+radius||z>b.maxZ-radius},lineClear(){return true}}}
function place(g,dx=5){const d=g.level1.danger;Object.assign(d,{area:g.level1.area,active:true,spawnAttempted:true,x:g.player.x+dx,z:g.player.z,phase:'dark',grace:0,routeTimer:0,lastPlayer:{...g.player}});g.level1.phase='dark';return d}

test('prewarm builds all six sector graphs without gameplay mutations, then reuses them',()=>{assert.equal(LEVEL_ONE_AREAS.length,6);const g=make(),before=JSON.stringify({player:g.player,level1:g.level1,events:g.events});prepareLevelOneDanger(g);assert.equal(JSON.stringify({player:g.player,level1:g.level1,events:g.events}),before);const calls=g.calls;assert(calls>1000);prepareLevelOneDanger(g);assert.equal(g.calls,calls);g.level1.danger=resetLevelOneDanger();prepareLevelOneDanger(g);assert.equal(g.calls,calls)});
test('each area has one distant in-bounds presence with two seconds stationary grace',()=>{for(const a of LEVEL_ONE_AREAS){const g=make(a);g.level1.phase='dark';tick(g,.025);const d=g.level1.danger;assert(d.active,`area ${a.id}`);assert(Math.hypot(d.x-g.player.x,d.z-g.player.z)>=8);assert(d.x>=a.bounds.minX&&d.x<=a.bounds.maxX&&d.z>=a.bounds.minZ&&d.z<=a.bounds.maxZ);assert(!isLevelOneSheltered(d.x,d.z));const p={x:d.x,z:d.z};tick(g,1.9);assert.deepEqual({x:d.x,z:d.z},p);assert.equal(d.contact,0)}});
test('area transition hides the old presence and preserves a global checkpoint',()=>{const g=make(),d=place(g);d.checkpoint={x:123,z:456,yaw:1};g.level1.area=LEVEL_ONE_AREAS[1].id;Object.assign(g.player,exposed(LEVEL_ONE_AREAS[1]));tick(g,.025);assert(!d.active);assert.equal(d.path.length,0);assert.deepEqual(d.checkpoint,{x:123,z:456,yaw:1});tick(g,.025);assert(d.active);assert(d.z<=LEVEL_ONE_AREAS[1].bounds.maxZ)});
test('all sector shelters update checkpoints and exclude a presence',()=>{for(const a of LEVEL_ONE_AREAS)for(const s of a.shelters){const g=make(a);Object.assign(g.player,{x:(s.minX+s.maxX)/2,z:(s.minZ+s.maxZ)/2,yaw:1});tick(g,.025);assert.deepEqual(g.level1.danger.checkpoint,{x:g.player.x,z:g.player.z,yaw:1});g.level1.phase='dark';tick(g,3);const d=g.level1.danger;assert(!d.active||!isLevelOneSheltered(d.x,d.z));assert.equal(d.contact,0);assert.equal(g.mode,'playing')}});
test('breaking sight preserves last observation; quiet distant movement is not tracked',()=>{const g=make(),d=place(g,5);d.grace=100;tick(g,.025);const seen={...d.lastSeen};g.lineClear=()=>false;g.player.x-=3;tick(g,.025);assert.deepEqual(d.lastSeen,seen);tick(g,3);assert.equal(d.memory,0);assert.deepEqual(d.lastSeen,seen);g.level1.sprinting=true;g.player.x+=.1;tick(g,.025);assert.deepEqual(d.lastSeen,{x:g.player.x,z:g.player.z});assert.equal(d.memory,2.5)});
test('a lost target is investigated once and the presence then waits',()=>{const g=make(),d=place(g,5);tick(g,.025);g.lineClear=()=>false;g.player.x=-8;tick(g,6);assert.equal(d.lastSeen,null);assert.equal(d.path.length,0);const stopped={x:d.x,z:d.z};g.player.z-=2;tick(g,2);assert.deepEqual({x:d.x,z:d.z},stopped);assert.equal(g.mode,'playing')});
test('normal walking is audible only very near, and sprinting has a 14m limit',()=>{for(const [distance,sprint,heard]of[[3,false,true],[5,false,false],[13,true,true],[15,true,false]]){const g=make();g.player.x=-7;const d=place(g,distance);d.grace=100;g.lineClear=()=>false;g.level1.sprinting=sprint;g.player.z+=.02;tick(g,.025);assert.equal(!!d.lastSeen,heard,`${distance}m sprint=${sprint}`)}});
test('contact needs 0.7 seconds, resets on separation, and light removes danger',()=>{const g=make(),d=place(g,.6);d.routeTimer=Infinity;tick(g,.5);assert.equal(g.mode,'playing');g.player.x-=2;tick(g,.025);assert.equal(d.contact,0);g.player.x+=2;tick(g,.725);assert.equal(g.mode,'lost');assert.equal(g.level1.failure,'entity');g.mode='playing';g.level1.phase='lit';tick(g,.025);assert(!d.active);assert.equal(d.proximity,0)});
test('blocked line of sight cannot deal contact damage',()=>{const g=make(),d=place(g,.6);g.lineClear=()=>false;tick(g,2);assert.equal(g.mode,'playing');assert.equal(d.contact,0)});
test('pause, phone and inventory freeze danger exactly',()=>{for(const patch of[{mode:'paused'},{phoneOpenId:'phone'},{inventoryOpen:true}]){const g=make();place(g);Object.assign(g,patch);const before=JSON.stringify(g.level1);tick(g,3);assert.equal(JSON.stringify(g.level1),before)}});
test('actual layout prewarm and sector movement stay collision-free',async()=>{const {zoneCollides}=await import('../dist/zones.js');const g=make();g.collides=(x,z,o={})=>zoneCollides('level1',x,z,o.radius??0);const start=performance.now();prepareLevelOneDanger(g);console.log(`Six sector navigation prewarm: ${(performance.now()-start).toFixed(1)} ms`);for(const a of LEVEL_ONE_AREAS){g.level1.area=a.id;g.level1.danger=resetLevelOneDanger();let p;for(let z=a.bounds.maxZ-10;z>a.bounds.minZ+10&&!p;z-=2)for(let x=-14;x<=14&&!p;x+=2)if(!isLevelOneSheltered(x,z)&&!g.collides(x,z,{radius:.3}))p={x,z};assert(p,`area ${a.id} has walkable exposed floor`);Object.assign(g.player,p);g.level1.phase='dark';for(let i=0;i<160;i++){const before={x:g.level1.danger.x,z:g.level1.danger.z,active:g.level1.danger.active};updateLevelOneDanger(g,.025);const d=g.level1.danger;if(i===0)assert(d.active,`area ${a.id} can spawn`);if(before.active&&d.active)assert(Math.hypot(d.x-before.x,d.z-before.z)<=1.6*.025+1e-9);if(d.active){assert(!g.collides(d.x,d.z,{radius:.25}));assert(!isLevelOneSheltered(d.x,d.z));assert(d.z>=a.bounds.minZ&&d.z<=a.bounds.maxZ)}}}});
