import test from 'node:test';
import assert from 'node:assert/strict';
import {resetLevelOneDanger,updateLevelOneDanger,levelOneSheltered} from '../dist/level-one-danger.js';
function make(walls=[]){return{zone:'level1',mode:'playing',player:{x:3,z:-8,yaw:0},events:[],food:100,hydration:100,level1:{elapsed:0,phase:'lit',danger:resetLevelOneDanger()},collides(x,z,{radius=0}={}){return x<-8+radius||x>8-radius||z<-44+radius||z>6-radius||walls.some(w=>Math.abs(x-w.x)<w.w/2+radius&&Math.abs(z-w.z)<w.d/2+radius)},lineClear(x,z){const p=this.player,n=Math.ceil(Math.hypot(x-p.x,z-p.z)/.025);for(let k=1;k<n;k++)if(this.collides(p.x+(x-p.x)*k/n,p.z+(z-p.z)*k/n,{radius:0}))return false;return true}}}
const tick=(g,t)=>{for(let i=0;i<Math.round(t/.025);i++)updateLevelOneDanger(g,.025)};
function place(g,x,z){Object.assign(g.level1.danger,{active:true,spawnAttempted:true,x,z,grace:0,routeTimer:Infinity,path:[]});g.level1.phase='dark'}
test('all three refuges protect their full region and checkpoints update',()=>{for(const[x,z]of[[-5,-27],[0,4],[6,-20]]){assert(levelOneSheltered(x,z));const g=make();Object.assign(g.player,{x,z});tick(g,.025);assert.deepEqual(g.level1.danger.checkpoint,{x,z,yaw:0})}assert(!levelOneSheltered(0,-10))});
test('warning is non-damaging and actual blackout arrival is deterministic, collision-free and distant',()=>{const a=make(),b=make();a.level1.phase=b.level1.phase='warning';tick(a,5);tick(b,5);assert(!a.level1.danger.active);assert.equal(a.events.length,1);a.level1.phase=b.level1.phase='dark';tick(a,.025);tick(b,.025);assert.deepEqual(a.level1.danger,b.level1.danger);const d=a.level1.danger;assert(d.active);assert(Math.hypot(d.x-a.player.x,d.z-a.player.z)>7.95);assert(a.lineClear(d.x,d.z));assert(!a.collides(d.x,d.z,{radius:.25}));assert.equal(d.contact,0)});
test('darkness alone never drains health and restoring light removes the presence immediately',()=>{const g=make();g.level1.phase='dark';tick(g,.025);assert(g.level1.danger.active);assert.equal(g.level1.danger.grace,1.975);g.level1.phase='lit';tick(g,.025);assert(!g.level1.danger.active);assert.equal(g.level1.danger.proximity,0);assert.equal(g.level1.danger.contact,0);assert.equal(g.food,100);assert.equal(g.hydration,100);tick(g,2);assert.equal(g.events.length,2)});
test('two second grace and sustained contact are required for capture',()=>{const g=make();place(g,3.5,-8);g.level1.danger.grace=2;tick(g,2.6);assert.equal(g.mode,'playing');tick(g,.15);assert.equal(g.mode,'lost');assert.equal(g.level1.failure,'entity');assert.equal(g.events.at(-1),'level1-entity-caught')});
test('contact resets when broken and cannot catch through opaque walls',()=>{const g=make();place(g,3.5,-8);tick(g,.5);g.player.x=1;tick(g,.025);assert.equal(g.level1.danger.contact,0);g.player.x=3;tick(g,.5);assert.equal(g.mode,'playing');const w=make([{x:0,z:-8,w:.02,d:4}]);Object.assign(w.player,{x:-.3,z:-8});place(w,.3,-8);tick(w,3);assert.equal(w.mode,'playing');assert.equal(w.level1.danger.contact,0);assert.equal(w.level1.danger.proximity,0)});
test('pause, backpack, phone, other zones, invalid dt never advance entity',()=>{for(const patch of[{mode:'paused'},{inventoryOpen:true},{phoneOpenId:'phone-1'},{zone:'hub'}]){const g=make();place(g,3.5,-8);Object.assign(g,patch);const before=JSON.stringify(g.level1.danger);tick(g,4);assert.equal(JSON.stringify(g.level1.danger),before)}const g=make();for(const dt of[NaN,0,-1,Infinity])updateLevelOneDanger(g,dt);assert(!g.level1.danger.active)});
test('entity cannot enter refuges or capture occupants',()=>{const g=make();Object.assign(g.player,{x:0,z:2.1});place(g,0,1.7);g.level1.danger.routeTimer=0;tick(g,3);assert.equal(g.mode,'playing');assert.equal(g.level1.danger.contact,0);assert(!levelOneSheltered(g.level1.danger.x,g.level1.danger.z));assert.equal(g.level1.danger.z,1.7)});
test('bounded live navigation routes around a baffle without wall walking and remains slower than normal walking',()=>{const g=make([{x:0,z:-12,w:.3,d:8}]);Object.assign(g.player,{x:-3,z:-12});place(g,3,-12);g.level1.danger.routeTimer=0;let wentAround=false;for(let i=0;i<800&&g.mode==='playing';i++){const d=g.level1.danger,old={x:d.x,z:d.z};updateLevelOneDanger(g,.025);assert(!g.collides(d.x,d.z,{radius:.25}));assert(Math.hypot(d.x-old.x,d.z-old.z)<=1.6*.025+1e-9);if(d.z> -7.76||d.z< -16.24)wentAround=true}assert(wentAround);assert.equal(g.mode,'lost')});
test('a newly introduced obstacle invalidates the presence rather than teleporting it',()=>{const walls=[],g=make(walls);place(g,3,-10);walls.push({x:3,z:-10,w:1,d:1});tick(g,.025);assert(!g.level1.danger.active);assert.equal(g.mode,'playing')});
test('each reset owns its route and checkpoint with no cross-game cache',()=>{const a=resetLevelOneDanger(),b=resetLevelOneDanger();a.path.push({x:0,z:0});a.checkpoint.x=99;assert.equal(b.path.length,0);assert.equal(b.checkpoint.x,0)});

test('safe bypass is protected without replacing last room checkpoint',()=>{const g=make();g.level1.danger.checkpoint={x:-5,z:-27,yaw:1};for(const[x,z]of[[-5,-31],[-5,-37],[-3,-37]]){assert(levelOneSheltered(x,z));Object.assign(g.player,{x,z});tick(g,.025);assert.deepEqual(g.level1.danger.checkpoint,{x:-5,z:-27,yaw:1})}});
test('authoritative Level 1 baffles and props remain solid throughout a complete blackout',async()=>{const {zoneCollides}=await import('../dist/zones.js');for(const[x,z]of[[0,4.5],[5,-8],[-5,-14],[5,-20],[0,-28],[-5,-27],[0,-40]]){const g=make();g.collides=(x,z,options={})=>zoneCollides('level1',x,z,options.radius??0);Object.assign(g.player,{x,z});assert(!g.collides(x,z,{radius:.22}));g.level1.phase='warning';tick(g,.025);const d=g.level1.danger;if(d.active){assert(d.z>=-30);assert(Math.hypot(d.x-x,d.z-z)>8);assert(!g.collides(d.x,d.z,{radius:.25}))}g.level1.phase='dark';for(let k=0;k<320&&g.mode==='playing';k++){tick(g,.025);if(d.active){assert(!g.collides(d.x,d.z,{radius:.25}));assert(!levelOneSheltered(d.x,d.z))}}g.level1.phase='lit';g.mode='playing';tick(g,.025);assert(!d.active)}});
test('real Game stationary exposed player can be captured during its actual first blackout',async()=>{const {Game}=await import('../dist/game.js');const g=new Game(7);g.start();g.transitionZone('level1');Object.assign(g.player,{x:5,z:-3});g.level1.elapsed=13.98;for(let i=0;i<570&&g.mode==='playing';i++)g.update(.025,{});assert.equal(g.mode,'lost');assert.equal(g.level1.failure,'entity');assert(g.events.includes('level1-entity-caught'))});
test('real layout shelf corner does not trap path steering',async()=>{const {zoneCollides}=await import('../dist/zones.js');const g=make();g.collides=(x,z,o={})=>zoneCollides('level1',x,z,o.radius??0);Object.assign(g.player,{x:5,z:-8});g.level1.phase='dark';tick(g,8);assert(g.level1.danger.z< -6)});

test('physical presence blocks charging through it but permits retreat without capture',async()=>{
 const {Game}=await import('../dist/game.js');
 for(const retreat of [false,true]){
  const g=new Game(7);g.start();g.transitionZone('level1');Object.assign(g.player,{x:0,z:-14,yaw:0});g.level1.elapsed=23;g.level1.phase='dark';Object.assign(g.level1.danger,{active:true,spawnAttempted:true,x:0,z:-14.6,grace:0,routeTimer:Infinity,path:[],phase:'dark'});
  for(let i=0;i<40&&g.mode==='playing';i++)g.update(.025,{forward:retreat?-1:1});
  if(retreat){assert.equal(g.mode,'playing');assert(g.player.z> -13);assert.equal(g.level1.danger.contact,0)}else{assert.equal(g.mode,'lost');assert(g.player.z> -14.1);assert.equal(g.level1.failure,'entity')}
 }
});
